DROP DATABASE IF EXISTS MARS_DB;
CREATE DATABASE MARS_DB;
USE MARS_DB;

DROP TABLE IF EXISTS person;
CREATE TABLE person (
  person_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name      TEXT        NOT NULL,
  birth_date     DATE,
  gender         TEXT        CHECK (gender IN ('male','female','other','unknown')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Unstructured medical notes (many per person)
DROP TABLE IF EXISTS medical_note;
CREATE TABLE medical_note (
  note_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id      BIGINT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
  note_text      TEXT   NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);