DROP DATABASE IF EXISTS MARS_DB;
CREATE DATABASE MARS_DB;
USE MARS_DB;

DROP TABLE IF EXISTS person;
CREATE TABLE person (
  person_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fname          TEXT        NOT NULL,
  lname          TEXT        NOT NULL,
  gender         TEXT        CHECK (gender IN ('male','female','other','unknown')),
  birth_date     DATE,
  email          TEXT        UNIQUE,
  address        TEXT        NOT NULL,
  phone          TEXT,
  username       TEXT        UNIQUE NOT NULL,
  password       TEXT        NOT NULL,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TABLE IF EXISTS employee;
CREATE TABLE employee (
  employee_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       TEXT        UNIQUE NOT NULL,
  password       TEXT        NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- Unstructured medical notes (one per person)
DROP TABLE IF EXISTS medical_history;
CREATE TABLE medical_history (
  note_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id      BIGINT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
  blood_type     TEXT NOT NULL,
  medical_note      TEXT   NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- also one per person
DROP TABLE IF EXISTS allergies;
CREATE TABLE allergies (
  allergy_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id      BIGINT NOT NULL REFERENCES person(person_id) ON DELETE CASCADE,
  allergy_notes  TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);