DROP DATABASE IF EXISTS MARS_DB;
CREATE DATABASE MARS_DB;
USE MARS_DB;

DROP TABLE IF EXISTS person;
CREATE TABLE person (
  person_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fname          TEXT        NOT NULL,
  lname          TEXT        NOT NULL,
  gender         TEXT        CHECK (gender IN ('male','female','other','unknown')),
  birth_date     DATE,
  email          TEXT        UNIQUE,
  address        TEXT        NOT NULL,
  phone          TEXT,
  username       TEXT        UNIQUE NOT NULL,
  password       TEXT        NOT NULL,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  blood_type     TEXT NOT NULL,
  medical_note      TEXT,
  allergy_notes  TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TABLE IF EXISTS employee;
CREATE TABLE employee (
  employee_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       TEXT        UNIQUE NOT NULL,
  password       TEXT        NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
